name: authenticator
description: A minimalistic OTP generator.

version: 1.0.0+11

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^2.0.1
  base32: ^1.1.1
  cupertino_icons: ^0.1.2
  flutter_secure_storage: ^3.3.1+1
  provider: ^4.0.4
  sentry: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/issuers/

  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
    - family: Kameron
      fonts:
        - asset: assets/fonts/Kameron-Bold.ttf
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
