name: authenticator
description: A new Flutter project.

version: 1.0.0+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^1.0.0
  base32: ^1.0.1
  crypto: ^2.0.6
  cupertino_icons: ^0.1.2
  flutter_secure_storage: ^3.2.1+1
  flutter_slidable: "^0.5.3"
  sentry: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Karla
      fonts:
        - asset: fonts/Karla-Regular.ttf
    - family: Kameron
      fonts:
        - asset: fonts/Kameron-Bold.ttf
    - family: Varela
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf

  assets:
    - assets/issuers/